org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
# For Gradle 5.6.4 + AGP 3.5.4 use JDK 11
org.gradle.java.home=C:\\Users\\ikeife\\.jabba\\jdk\\openjdk@1.11.0
android.useAndroidX=true
android.enableJetifier=true
systemProp.gradle.internal.http.insecure=true
systemProp.gradle.internal.http.acceptUntrustedServerCertificate=true
